<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

In [ ]:
# run this cell first
import numpy as np



---



---



---



# Exercise A:




### 1- Construct a Ndarray  of shape (3, 2) filled with **8**, Then set element (0, 1) to 10, and element (1, 0) to 100

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x=np.full((3,2),8)
x[0,1]=10
x[1,0]=100
x
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[  8,  10],
       [100,   8],
       [  8,   8]])

### 2- Create a 64-bit floating-point Ndarray of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
np.linspace(10,20,6)
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10., 12., 14., 16., 18., 20.])

### 3- Create a vector with values ranging from 10 to 49

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x =np.arange(50)
x =x[x>=10]
x
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4- Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x =np.arange(9).reshape(3,3)
x
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5- Create a 10x10 array with random values and print the trace value and the mean values of each row

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

x=np.random.random((10,10))
print(np.trace(x))
#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

3.5972049614666393


### 6- Create a Ndarray array of size (5, 5) with all **1** on the borders and all **0** in the inside


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x =np.zeros((5,5))
x[0]=1
x[-1]=1
x[:,0]=1
x[:,-1]=1
x
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 7- Create random vector of size 10 and replace the maximum value by 0

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x=np.random.random(10)
x[x.argmax()]=0
x

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([0.76978862, 0.16426905, 0.31016702, 0.41756478, 0.31779743,
       0.14791595, 0.5913324 , 0.02353595, 0.        , 0.50406696])

### 8- Normalize a 5x5 random matrix
Hint: subtract the mean and devide by the standard deviation

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
x =np.random.random((5,5))
x_mean=np.mean(x)
x_std = np.std(x)
norm_x =(x-x_mean)/x_std
norm_x

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[ 1.37347323,  0.25264156, -0.87349294, -1.65273127,  1.4293612 ],
       [-1.21275126,  1.3557792 ,  1.08509354,  0.58980815, -1.0775575 ],
       [-1.29147902, -1.70719096, -1.35779262,  0.00536013, -0.47045045],
       [ 0.99467067, -0.66624016, -0.06337232, -0.31841546,  0.67499293],
       [-0.14492012,  0.16340243,  0.99664892,  0.96882277,  0.94633938]])

### 9- Create a random 5x2 matrix representing cartesian coordinates and print an array **"polar"** with same shape representing the converted polar coordinates.

Hints:

X represent the first column.

Y represent the second column.

Compute:

$$ R = \sqrt{X^2 + Y^2} $$

$$ T = \arctan{(Y, X)} $$


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
m =np.random.random((5,2))
x=m[:,0]
y=m[:,1]
R=np.sqrt(x**2 +y**2)
T=np.arctan2(y,x)
polar = np.dstack((R,T))
polar
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[[0.97781253, 1.47303919],
        [0.88539287, 0.30090966],
        [1.26294433, 0.85147795],
        [1.00504193, 0.28021173],
        [0.19327217, 0.19608701]]])



---



---



---



### 10- Write a function that normalizes the columns of a matrix. It should compute the mean and standard deviation of each column, then subtract the mean and divide by the standard deviation for each element in the column. 

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Your implementation should not use any loops; instead you should use reduction and broadcasting operations.

In [ ]:
x = np.array([[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]])

In [ ]:


################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def normalize_columns(x):
  mean =x.mean(axis=0)
  std =x.std(axis=0)
  norm =(x-mean)/std
  return norm




  # x: (input) Ndarray of shape (N, M) (don't modefy it: use copy())
  # y: (return) Ndarray of shape (N, M) normalized by the columns
  
  #your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1.224744871391589, 1.224744871391589], [1.224744871391589, -1.224744871391589, -1.224744871391589], [-1.224744871391589, 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
[[  0.  30. 600.]
 [  1.  10. 200.]
 [ -1.  20. 400.]]
Here is y0:
[[ 0.          1.22474487  1.22474487]
 [ 1.22474487 -1.22474487 -1.22474487]
 [-1.22474487  0.          0.        ]]




---



---



---



### 11- creates a function that returns a matrix of **one-hot vectors** from a list of Python integers. A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

### For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

### Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def make_one_hot(x):
  size =np.max(x)+1
  print(size)
  print("****")
  new_x =np.array(x)
  print(new_x)
  idx =np.where(new_x==new_x)
  print(f'{idx} the index')
  ohe =np.zeros((size-1,size))
  ohe[idx,x]=1
  return ohe
  


  #x: (input) A list of n ints
  
  #your code should be here
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
y0

5
****
[1 4 3 2]
(array([0, 1, 2, 3]),) the index


array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

Run the following cell to check your implementation, you must see 'all checks pass!' message

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

5
****
[1 4 3 2]
(array([0, 1, 2, 3]),) the index
Here is y0:
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
8
****
[1 3 5 7 6 2]
(array([0, 1, 2, 3, 4, 5]),) the index

Here is y1:
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
all checks pass!




---



---



---



# Exercise B:

### Maximum Likelihood
Find the maximum likelihood estimation of parameters $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N
$$

Steps to follow:


1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Compute the maximum likelihood estimation of parameters $\boldsymbol\theta$ following the equation and assign it to a variable called **theta**

$$
\boldsymbol\theta = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol y\in\mathbb{R}^D
$$

4. print the value of **theta**

Hint: check the inverse method from the linear algebra module in Numpy

In [ ]:
################################################################################
# TODO: Compute the maximum likelihood estimation of parameters theta
#       following the equation
################################################################################
x =np.random.randn(10,5)
y =np.ones((10,1))
theta  =np.linalg.inv(x.T@x)@(x.T@y)
print(theta)

#your code should be here

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

[[ 0.33320029]
 [-0.60357389]
 [-0.45839431]
 [ 0.1899204 ]
 [-0.48163679]]




---



---



---



# Exercise B:

### The Log Likelihood

Find the log likelihood estimation for input X, label y, parameterized by $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N \quad \boldsymbol \theta  \in\mathbb{R}^D
$$

steps to follow:

1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Initialize Ndarray **theta** randomly with shape D = 5 and reshape it to have the shape (D, 1).
4.   Compute the the probability of a all data points $(\boldsymbol x, y)$ being of class 1, given by

$$p(y = 1 | \boldsymbol X, \boldsymbol\theta) = 1.0/(1.0+\exp(- \boldsymbol X \boldsymbol \theta))$$

5. compute the log Likelihood, given by:
$$\log p(\boldsymbol y|\boldsymbol X, \boldsymbol\theta) = \sum_i y_i * \log (p(y = 1 | \boldsymbol x, \boldsymbol\theta) + (1 - y_i) * \log ( 1 - p(y = 1 | \boldsymbol x, \boldsymbol\theta))$$

6. print the log Likelihood

In [ ]:
################################################################################
# TODO: Compute the log likelihood 
#    
################################################################################


#your code should be here
x =np.random.randn(10,5)
#print(x)
y =np.ones((10,1))
#print("**********************************")
#print(y)
theta =np.random.random((5,1))
pr =1.0/(1.0 +np.exp(-x@theta))
logpr =np.sum(y*np.log(pr)+(1.0-y)*np.log(1-pr))
#print("************************************")
print(logpr)


 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

[[ 0.74215646  0.19702398  2.340987    0.45038197  1.7922427 ]
 [ 0.45316983 -0.70206179  0.2089869  -0.44675242  0.45896705]
 [ 0.16948911 -0.89022933  2.57323     0.01247576 -1.57253636]
 [-0.34876691 -0.01026064  1.13627173  1.89426929 -1.01982859]
 [-0.98399903  0.15986488  0.05459021  0.38934659  1.86394253]
 [ 0.59953528 -0.05050186 -1.07630511  0.05319519  1.0223362 ]
 [-2.78064771 -0.10031491  0.02694777 -0.43336346  0.72145835]
 [ 0.68166813  1.77815058  1.23375622 -1.24676001 -1.96868173]
 [-0.83454924 -0.57540559 -0.65159958  0.03836248  0.02140103]
 [-1.70426134 -0.51316496  1.29864775  1.99487861 -0.10549219]]
-7.744126516525118
